version: '2.2'
services:
  es01:
    image: elastic/elasticsearch:7.8.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=esb-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  es02:
    image: elastic/elasticsearch:7.8.0
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=esb-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      - elastic
  es03:
    image: elastic/elasticsearch:7.8.0
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=esb-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
    volumes:
      - data03:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana: 
     image: elastic/kibana:7.8.0
     container_name: kibana
     ports:
     - 5601:5601
     networks:
     - elastic
     environment:
      - xpack.monitoring.enabled=true
     depends_on:
      - es01
      - es02
      - es03

  logstash:
     image: elastic/logstash:7.8.0
     container_name: logstash 
     environment:
      - xpack.monitoring.enabled=false
     depends_on:
      - es01
      - es02
      - es03

     ports:
      - 5040-5100:5040-5100
     networks: 
      - elastic  
volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  elastic:
    driver: bridge
